### ISSUE TITLE
Installation tutorial video

### ISSUE THREAD

**Issue by mailed91** [ProcessMaker/processmaker#3644]
Can you make me a video of its complete installation?
I did not know how to install - when I install I get a lot of errors that the software does not work properly.
I am using ubuntu 20.4.
thanks.

**Comment by ericlima-mvv** [comment]
A video tutorial looks great, but even instruction in a blog post would do it, if they were clear enough.
I'm trying to use it on a **_docker-compose environment_** according to the instructions on [this DockerHub page](https://hub.docker.com/r/processmaker/pm4-core) to no avail... Maybe I'm missing more info.

It's also not that clear if the image is from the Community edition or not.

The closest I ever got was following [this blog post](https://dev.to/mesadhan/processmaker-bpm-workflow-with-docker-4jpp) but it's already obsolete as it still uses the 3.5 version.

If there were clear official instructions on running each the Enterprise and the Community versions, it would make our work much easier.

**Comment by cybrpimp** [comment]
Looking for the same.  Gettings lots of errors and can not install.   Trying to switch from Camunda.


143 error code ELIFECYCLE
144 error errno 1
145 error @processmaker/processmaker@4.1.0 postinstall: `mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled`
145 error Exit status 1
146 error Failed at the @processmaker/processmaker@4.1.0 postinstall script.
146 error This is probably not a problem with npm. There is likely additional logging output above.
147 verbose exit [ 1, true ]

**Comment by ericlima-mvv** [comment]
Well @cybrpimp, I actually got it running. ~~But at the current state, they removed so many functions from the community edition I'm thinking of swithing **to camunda**~~ 

Here's some changes I did to get 4.0.17 running  on docker-compose, **I don't recommend doing this, as it's just a series of dumb overrides I had to do, to actually see something other than a bunch of errors, but Yeah, it at least started smoothly after a lot of compilation stuff ~~~(also I should have just made a gist sample instead of pasting tons of code in a comment, but i'm lazy):

**docker-compose.yml**
```yml
 version: '3.9'
 networks:
     pmnet:
 volumes:
     mysql-data:
     docker-data:
     processmaker-data:
 services:
     mysql:
         image: mysql:5.7
         ports:
             - '3306:3306'
         environment:
             MYSQL_ROOT_PASSWORD: P4ssW0rd
             MYSQL_DATABASE: pm4
             MYSQL_USER: pm4_user
             MYSQL_PASSWORD: pm4_password
         networks:
             - pmnet
         volumes:
             - mysql-data:/var/lib/mysql
     redis:
         image: redis:6
         ports:
             - '6379:6379'
         networks:
             - pmnet
     docker:
         image: docker:20-dind
         privileged: true
         ports:
             - '2376:2376'
         networks:
             - pmnet
         volumes:
             - ./certs:/certs
             - docker-data:/var/lib/docker
         environment:
             DOCKER_TLS_CERTDIR: '/certs'
     processmaker:
         image: processmaker/pm4-core:4.0-dev
         ports:
             - '8080:443'
         depends_on:
             - mysql
             - redis
             - docker
         networks:
             - pmnet
         volumes:
             - ./certs:/certs/
             - ./.env:/opt/processmaker/.env
             - processmaker-data:/opt/processmaker/storage
             - ./pm-entrypoint.sh:/usr/bin/pm-entrypoint.sh
             - ./test-services.sh:/bin/test-services.sh
             - ./database.php:/opt/processmaker/config/database.php
         environment:
             WAIT_FOR_DEPENDENTS: 1
             DOCKER_HOST: 'tcp://docker:2376'
             DOCKER_CERT_PATH: '/certs/client'
             DOCKER_TLS_VERIFY: 1
             NO_PROXY: '127.0.0.1,localhost,docker:2376'
```

**.env**
```ini
APP_DEBUG=FALSE
APP_NAME="ProcessMaker 4.0.17"
APP_ENV=local
APP_KEY=base64:IXNgKSZOSuMGzaCquw456hGJ95J9pQ2ONlDnBqz60tI=
APP_URL=https://localhost:8080

BROADCAST_DRIVER=pusher
BROADCASTER_HOST=
BROADCASTER_KEY=
LARAVEL_ECHO_SERVER_AUTH_HOST=https://pm4.mgt.processmaker.net
LARAVEL_ECHO_SERVER_PORT=6001
LARAVEL_ECHO_SERVER_DEBUG=FALSE
PUSHER_APP_ID=1051355
PUSHER_APP_KEY=c2045b0033cb0598b5f0
PUSHER_APP_SECRET=930f2416e4ac7dcbd630
PUSHER_CLUSTER=mt1
PUSHER_TLS=FALSE
PUSHER_DEBUG=FALSE
APP_TIMEZONE=UTC
DATE_FORMAT="m/d/Y H:i"
MAIN_LOGO_PATH="/img/processmaker_logo.png"
ICON_PATH_PATH="/img/processmaker_icon.png"
LOGIN_LOGO_PATH="img/processmaker_login.png"
REDIS_CLIENT=predis
REDIS_HOST=redis
REDIS_PREFIX=
HORIZON_PREFIX=pm4:
API_TIMEOUT=5000
DB_HOSTNAME=mysql
DB_PORT=3306
DB_DATABASE=pm4
DB_USERNAME=pm4_user
DB_PASSWORD=pm4_password
DB_DRIVER=mysql
DATA_DB_DRIVER=mysql
DATA_DB_HOST=mysql
DATA_DB_PORT=3306
DATA_DB_DATABASE=pm4
DATA_DB_USERNAME=pm4_user
DATA_DB_PASSWORD=pm4_password
DATA_DB_ENGINE=InnoDB
TELESCOPE_ENABLED=FALSE
PROCESSMAKER_SCRIPTS_HOME=/opt/processmaker/storage/app/scripts
DOCKER_HOST_URL=https://localhost:8080
HOME=/opt/processmaker

SCOUT_QUEUE=true

NODE_BIN_PATH=/bin/node
MAIL_DRIVER=
MAIL_HOST=
MAIL_PORT==
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=

PROXIES=*
```

**database.php**
```php
<?php

switch(env('DATA_DB_DRIVER', 'mysql')) {
    case 'pgsql':
        $charset = 'utf8';
        $collation = null;
        break;
    case 'sqlsrv':
        $charset = null;
        $collation = null;
        break;
    default:
        $charset = 'utf8mb4';
        $collation = 'utf8mb4_unicode_ci';
        break;
}

return [
    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */
    'default' => env('DB_CONNECTION', 'processmaker'),
    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */
    'connections' => [
        'processmaker' => [
            'driver' => env('DB_DRIVER', 'mysql'),
            'host' => env('DB_HOSTNAME', 'mysql'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'pm4'),
            'username' => env('DB_USERNAME', 'pm4_user'),
            'password' => env('DB_PASSWORD', 'pm4_password'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => 'InnoDB',
        ],
        'data' => [
            'driver' => env('DATA_DB_DRIVER', 'mysql'),
            'host' => env('DATA_DB_HOST', 'mysql'),
            'port' => env('DATA_DB_PORT','3306'),
            'database' => env('DATA_DB_DATABASE','pm4'),
            'username' => env('DATA_DB_USERNAME','pm4_user'),
            'password' => env('DATA_DB_PASSWORD','pm4_password'),
            'unix_socket' => env('DATA_DB_SOCKET',''),
            'charset' => $charset,
            'collation' => $collation,
            'schema' => env('DATA_DB_SCHEMA'),
            'engine' => env('DATA_DB_ENGINE','InnoDB'),
            'date_format' => env('DATA_DB_DATE_FORMAT'),
        ]
    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */
    'migrations' => 'migrations',
    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */
    'redis' => [
        'client' => env('REDIS_CLIENT', 'predis'),
        'options' => [
            'prefix' => env('REDIS_PREFIX', '')
        ],
        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => 0,
        ],
    ],
];
```

**pm-entrypoint.sh**
```shell
#!/bin/bash

set -a
source /opt/processmaker/.env
set +a

if [ $WAIT_FOR_DEPENDENTS == "1" ]; then
    sh /bin/test-services.sh  
fi

#hold up, bro, u goin to fast...
sleep 5
sleep 5
sleep 5

# Initialize ProcessMaker
sudo -u nginx php /opt/processmaker/artisan config:clear
sleep 5
sudo -u nginx php /opt/processmaker/artisan cache:clear
sleep 5
sudo -u nginx php /opt/processmaker/artisan migrate
sleep 5
sudo -u nginx cd /opt/processmaker && php /opt/processmaker/artisan db:seed
sleep 5
sudo -u nginx php /opt/processmaker/artisan passport:install
sleep 5
sudo -u nginx php /opt/processmaker/artisan storage:link


echo "ProcessMaker Loading Complete!"
/usr/bin/supervisord -c /etc/supervisord.conf
```

**test-services.sh**
```shell
#!/bin/bash
echo "Start waiting for MySQL"
until mysql -h $DB_HOSTNAME -u$DB_USERNAME -p$DB_PASSWORD -e "SELECT 1;"; do
    echo "MySQL is unavailable - sleeping"
    sleep 1
done
echo "MySQL is ready to accept connections"

echo "Start waiting for Redis"
until redis-cli -h $REDIS_HOST ping; do
    echo "Redis is unavailable - sleeping"
    sleep 1
done
echo "Redis is ready"
```
